name: Build Docker image

on:
  push:
    branches: [main]
    tags: [v*]

  pull_request:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/build.yml

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    outputs:
      image-version: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/aelesbao/redis
          tags: |
            type=semver,pattern={{version}}
            type=sha
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
